{{- if and .Values.db.enabled .Values.db.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-postgres
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.db.persistence.storageClassName }}
  storageClassName: {{ .Values.db.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
{{- end }}
